name: tblr_bnch
channels:
- defaults
dependencies:
- python=3.10
- numpy=1.26.4
- matplotlib=3.5.2
- requests=2.28.1
- decorator=5.1.1
- scikit-learn
- ipykernel
- ipywidgets
- lightgbm
- pip
- pip:
  - tabpfn
  - tabpfn-client